### ISSUE TITLE
Marlin binaries

### ISSUE THREAD

**Issue by susisstrolch** [Psychokiller1888/Vertex-Delta-Firmware#1]
Please, can you also share the binaries?

**Comment by Psychokiller1888** [comment]
I never compiled them, this is WIP and I did not have time to finish unfortunately

**Comment by susisstrolch** [comment]
What a pitty!

**Comment by Psychokiller1888** [comment]
This is open source, feel free to compile and share :)

**Comment by Psychokiller1888** [comment]
Compiled https://github.com/Psychokiller1888/Vertex-Delta-Firmware/releases/tag/v0.2_alpha
