### ISSUE TITLE
Display falls back to SD-Menue after print

### ISSUE THREAD

**Issue by susisstrolch** [Psychokiller1888/Vertex-Delta-Firmware#13]
Steps to produce:
- Start „Print from SD“
- Select gcode  

During print the Status is displayed 
After the print Display shows the SD directory instead of print summary

**Comment by Psychokiller1888** [comment]
Yeah, that's a wanted feature

**Comment by chuebsch** [comment]
```C++
 define SD_REPRINT_LAST_SELECTED_FILE
```
in Configuration_adv.h 
enables this feature. It is nice if you need to print the same gcode multiple times and there are many gcodes on your SD-card. I agree it would be even nicer when the status screen is there after the print but the old file is preselected when entering 'Print from SD card'. Just comment it out if you don't like it.
