### ISSUE TITLE
all values for DELTA_* values MUST be floating point, so always have a decimal point in them...

### ISSUE THREAD

**Issue by chuebsch** [Psychokiller1888/Vertex-Delta-Firmware#2]
Nice work but here is some issue: 
In Configuration.h in line 521 a comment says: 
'''
// NOTE NB all values for DELTA_* values MUST be floating point, so always have a decimal point in them
'''

line 539 is:
'''  
#define DELTA_DIAGONAL_ROD 207 // mm 
'''
but should be:
'''
#define DELTA_DIAGONAL_ROD 207.0 // mm 
'''

**Comment by Psychokiller1888** [comment]
Thank you!

Though it wasn't an issue, as this is transformed by the eeprom loading
