### ISSUE TITLE
Probing failed / Leveling Failed

### ISSUE THREAD

**Issue by chuebsch** [Psychokiller1888/Vertex-Delta-Firmware#7]
As my DELTA_HEIGHT is 311mm (after implementing Dr_Vegetables Sleds With Drylin Bushings) 
I got: 
```
Error:Probing Failed 
Correct delta settings with M665 and M666
```
After: 
```
M665 L207.00 R107.70 H311.03
M666 X0.00 Y-0.38 Z-0.12
M500
```
it worked. 
Now my K8800 is printing a test print, sounds crazy but looks nice so far. :+1:

**Comment by Psychokiller1888** [comment]
Yes, but you can set this custom delta height in your menus. Go to control->delta calibration->delta settings and save the settings then. To prevent it you can also first get the delta height from calibrate menu and then only auto calibrate
