### ISSUE TITLE
Annoying extra click on Filament change

### ISSUE THREAD

**Issue by chuebsch** [Psychokiller1888/Vertex-Delta-Firmware#9]
![dsc_1023](https://user-images.githubusercontent.com/16302835/51033630-549e6f80-15a4-11e9-93d4-629a0b31db11.JPG)

When I choose 'Tune->Change Filament' I see the above menu and need to scroll down to 'Change filament' and click it. I want that it just start the M600 routine directly.

**Comment by Psychokiller1888** [comment]
Ok, can do :)
